# -*- coding: utf-8 -*-
"""HasancanSoyturk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FKUv0SvuIYaqLpb7H5s9wMFETnSYMHbb

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""



"""Describe what an algorithm is."""

An algorithm is a list of rules to follow in order to solve a probles.

"""Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]"""

#BruteForce includes straightforward calculation based on the proper design content, the description of the problem and the definition of the relevant concepts, but this has no effect when dealing with more complex problems. It is not the correct method to solve problems with extra-hierarchical structures and logical operations. But in algorithmic design ;If there is a problem in the middle of the process to solve it completely consists of.

"""In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice."""

# An algorithm is a series of instructions, often referred to as a “process,” which is to be followed when solving a particular problem. While technically not restricted by definition, the word is almost invariably associated with computers, since computer-processed algorithms can tackle much larger problems than a human, much more quickly. Since modern computing uses algorithms much more frequently than at any other point in human history, a field has grown up around their design, analysis, and refinement. The field of algorithm design requires a strong mathematical background, with computer science degrees being particularly sought-after qualifications. It offers a growing number of highly compensated career options, as the need for more (as well as more sophisticated) algorithms continues to increase.



"""Create a python dictionary for your name surname and year of birth."""

dict_hasancansoyturk = {'name':'hasancan','surname':'soyturk','birthday':'1991'}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

name = 'hasancan'
if name[0] == 'a' :
  print ("my initial is a!")
else:
  print("Hayir !")

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

surname = 'soyturk'
len(surname)%3 == 0
if len(surname)%3 == 0 :
  print("it is divisible")
else:
  print("not divisible")

"""Change your year of birth to 2678."""

my_dict = ['hasancan','soyturk',1991]
my_dict[2] = '2678'
print (my_dict)

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""